# Generated by Django 6.0.3 on 2026-04-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(max_length=100)),
                ('production_quantity', models.FloatField()),
                ('yield_amount', models.FloatField()),
                ('farm_price', models.FloatField()),
                ('year', models.IntegerField()),
                ('region', models.CharField(max_length=100)),
            ],
        ),
    ]
