# Generated by Django 6.0.3 on 2026-04-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cropdata',
            old_name='crop_type',
            new_name='crop',
        ),
        migrations.RemoveField(
            model_name='cropdata',
            name='farm_price',
        ),
        migrations.RemoveField(
            model_name='cropdata',
            name='production_quantity',
        ),
        migrations.AddField(
            model_name='cropdata',
            name='production',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropdata',
            name='yield_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
